# Generated by Django 4.1.7 on 2023-04-12 17:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='password',
            field=models.CharField(default=builtins.id, max_length=100),
            preserve_default=False,
        ),
    ]
