# Generated by Django 4.1.7 on 2023-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_image_loginforms_registrationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForms',
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
