# Generated by Django 4.1.7 on 2023-05-11 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_filter_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='static/Clothes_images/img')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
                ('filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.filter_price')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.filter_size')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.type')),
            ],
        ),
    ]
