# Generated by Django 4.1.7 on 2023-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tengri', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
